### ISSUE TITLE
Prepare Content: Convert metadata term

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/akumina-mynci#29]
Given a string, convert it into a guid and return both in the format:

```node
{
      Label: "<string>",
      TermGuid: "<guid>",
      WssId: '-1'
    }
```

- Takes a string
- Opens a local file `termstore-map.json` (could be CSV as well, or whatever format we want)
   - Just needs to have the term label and guid
- Finds the term in the file
   - If exists: Returns the formatted object
   - If not: Returns empty

**Old:**

Create a new `convertMetadata` method on the `AkuminaSite` class (I think this is the correct location since we will need to interact with SharePoint). The method should take in a search string and a term set name and return correctly formatted code for adding a term to a column in a SharePoint list.

## Inputs

- tag (string): Freeform search string to look for in the term set
- termset (string): Name of the SharePoint term set to look for the tag in

## Returns

```node
TBD
```

## Tasks

Still investigating this. Note that we appear to not have access to query the term store lists. So we may need to work just on formatting and have a translation file in the repo itself.

https://plumsail.com/docs/actions/v1.x/flow/how-tos/sharepoint/update-sp-item.html

**Comment by belaolsonNIH** [comment]
Metadata column format:
```
{
    Title: 'Metadata Test',
    metadata_column: {
      Label: "Engineering",
      TermGuid: "bed92ebe-2ba2-4cf6-b9d9-401bbd9f79ad",
      WssId: '-1'
    }
}
```
or
```
{
    Title: 'Metadata Test',
    metadata_column: {
      TermGuid: "bed92ebe-2ba2-4cf6-b9d9-401bbd9f79ad",
      WssId: '-1'
    }
}
```

**Comment by erikscottmeyer** [comment]
I set this up to work like the XML import function, so we could import any number of json files and they would be categorized as with XML files; here we just have one, taxonomy-topics.json.  
[taxonomy-topics.json](https://github.com/NCIOCPL/akumina-mynci/files/14271952/taxonomy-topics.json)

**Comment by erikscottmeyer** [comment]
Taxonomy-topics.json is file with dummy data; storing it in content with the xml files: 
[taxonomy-topics.json](https://github.com/NCIOCPL/akumina-mynci/files/14272235/taxonomy-topics.json)
