### ISSUE TITLE
Prepare Content: Convert person

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/akumina-mynci#31]
- Take in either an NIH AD username (ideal) or an NIH email (should work), hereafter "identifier"
- Check to see if we already have a users list cached
- If we don't have a users list cached, retrieve one via:

```node
var userList = sp.web.lists.getByTitle('User Information List');
const users = await userList.items.getAll();
/* console.log(users); */
```

Note: The user list has to come from SharePoint/akumina and won't be easy to get in the Drupal class itself. So it probably needs to get passed in on `prepareContent()` as an object.

- Look up the identifier in the user list and return the SharePoint user ID
- Return the SharePoint user ID

**Comment by erikscottmeyer** [comment]
Right now I'm only doing the substitution if the user is found; if not found, it falls back on the email address.  If this is a problem for imports we can use some default user ID when not found.  I also generate a list of all users being called somewhere  across the site (332).
