### ISSUE TITLE
Prepare Content: Image

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/akumina-mynci#32]
Create a `convertImage` function in the `prepareContent` method. It needs to:

- Take in an image file URL and, ideally, a description or alt text
- Run that URL through the URL converter to get the new URL 
- Format the response object in a way that matches what SharePoint expects. I believe [this is correct](https://plumsail.com/docs/actions/v1.x/flow/how-tos/sharepoint/update-sp-item.html#update-hyperlink-and-picture-columns-with-an-alternative-text).
- Return the formatted Image

**Comment by belaolsonNIH** [comment]
Picture format:
```
{
    Title: 'Image Test',
    Picture: {
      Description: "Test image",
      Url: "https://www.sharepoint.com/path/to/image"
    }
}
```

**Comment by jfrank-nih** [comment]
Closing this in favor of convertLink.
