### ISSUE TITLE
Prepare Content: Link

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/akumina-mynci#33]
Create a `convertImage` function in the `prepareContent` method. It needs to:

- Take in a link URL and text
- Run that URL through the URL converter to get the new URL (default to old URL if none exists, but log a warning)
- Format the response object in a way that matches what SharePoint expects. 

```
    link_column: {
      Description: "<description>",
      Url: "<url>"
    }
```

- Return the formatted URL

**Comment by belaolsonNIH** [comment]
Link format:
```
{
    Title: 'Link Test',
    link_column: {
      Description: "Google",
      Url: "https://www.google.com"
    }
}
```
