### ISSUE TITLE
Determine correct SharePoint format for column types

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/akumina-mynci#36]
Determine the correct SharePoint upload format for the following column types. I have linked to a place that I think has the correct format for some of them.

- Person
- Date
- [Managed Metadata](https://plumsail.com/docs/actions/v1.x/flow/how-tos/sharepoint/update-sp-item.html#update-managed-metadata-column-using-term-label-or-guid) (Taxonomy)
- [Link](https://plumsail.com/docs/actions/v1.x/flow/how-tos/sharepoint/update-sp-item.html#update-hyperlink-and-picture-columns-with-an-alternative-text)
- [Image](https://plumsail.com/docs/actions/v1.x/flow/how-tos/sharepoint/update-sp-item.html#update-hyperlink-and-picture-columns-with-an-alternative-text)

You can add columns to this list: https://nih.sharepoint.com/sites/myNCI-preprod/Lists/TEST_data_migration/AllItems.aspx

**Comment by belaolsonNIH** [comment]
Link format
```
{
    Title: 'Link Test',
    link_column: {
      Description: "Google",
      Url: "https://www.google.com"
    }
 }
```

**Comment by belaolsonNIH** [comment]
Date format
`{
    Title: 'Date Test',
    date_column: '10/20/2023'
  }`

**Comment by belaolsonNIH** [comment]
Picture format
```
{
    Title: 'Image Test',
    Picture: {
      Description: "Test image",
      Url: "https://www.nih.sharepoint.com/path/to/image"
    }
}
```

**Comment by belaolsonNIH** [comment]
Managed Metadata
```
{
    Title: 'Metadata Test',
    metadata_column: {
      Label: "Engineering",
      TermGuid: "bed92ebe-2ba2-4cf6-b9d9-401bbd9f79ad",
      WssId: '-1'
    }
}
```
OR
```
{
    Title: 'Metadata Test',
    metadata_column: {
      TermGuid: "bed92ebe-2ba2-4cf6-b9d9-401bbd9f79ad",
      WssId: '-1'
    }
}
```

**Comment by belaolsonNIH** [comment]
Person format
```
{
    Title: 'Person Test',
    person_columnId: 15
}
```
But ID is unique to the site
