### ISSUE TITLE
Drupal Content applyContentMap puts everything in an array

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/akumina-mynci#45]
the `applyContentMap` function is putting everything into an array.

https://github.com/NCIOCPL/akumina-mynci/blob/57bd69323d6ae3f4ef0528727dbe1a7d28758fa6/migration/src/lib/drupal-content.js#L262

The PNP import library expects to have strings or objects, depending on column type, in the item. 

I got away with the initial push by changing this:

https://github.com/NCIOCPL/akumina-mynci/blob/57bd69323d6ae3f4ef0528727dbe1a7d28758fa6/migration/src/lib/drupal-content.js#L293

to this:

```node
convertedItem[mapElement.SharePointColumn] = newData.toString();
```

But that doesn't work for all content types, some of which need a more complex type.

We need to make the function return a `convertedItem` where the value assigned to the column is just itself, not in an array.

**Comment by erikscottmeyer** [comment]
I set this up so that all returned values are either strings or objects with an array in them (this is because all convertedItems returning objects could potentially return more than one).
