### ISSUE TITLE
Reduce and Import Files

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/akumina-mynci#65]
**Background: Upload**

The [AkuminaSite.ImportFiles(listPath, items)](https://github.com/NCIOCPL/akumina-mynci/blob/9eb1939c8382c800ca86dc0fe77ed9cc332e8727/migration/src/lib/akumina-site.js#L63) method will allow us to import a file into Akumina. 

Unfortunately this cannot be done in batch as it involves an upload. So we have to do this in a loop. That said, the function supports taking in an array of items to import. The array should contain:

- Local path to the file to upload
- Name of the file to add in SharePoint
- Metadata for the item (this matches the same key/value format for adding items)

**Selecting Files Logic**

The logic for selecting files is similar for selecting which links to upload:

- We load all of the file URLs into the URL converter ([are we already doing this](https://github.com/NCIOCPL/akumina-mynci/blob/9eb1939c8382c800ca86dc0fe77ed9cc332e8727/migration/src/import-drupal.js#L40)?) **We should load the files in with both the interstitial page path from Drupal _and_ the final file path. There are links going to both in the old content.**
- As we process through all the other content, we identify any link to a file and then mark that file as "active"
- When we go to upload our files at the end, we only upload the active files. We want to abandon the rest.

I believe the logic for images is the same, though we may not need to do the interstitial pages into the URL converter. Then again, it probably doesn't hurt to do so.

**Upload Fields**

Since files and images don't have significant amounts of metadata, we don't need to worry about uploading a whole lot.

**Comment by erikscottmeyer** [comment]
I had to add a new Export Files view in Drupal; updated the xml export files to include Media Files and Media Images.  I believe everything is working, though there were only about ten files marked active; there were about 800 images.  All went across without incident.  Had to make new maps etc. for media Images and media files.

**Comment by erikscottmeyer** [comment]
[Uploading export-files.zip…]()
