### ISSUE TITLE
FriendlyUrlSearch field missing value in Blogs_AK and InternalPages_AK

### ISSUE THREAD

**Issue by belaolsonNIH** [NCIOCPL/akumina-mynci#67]
### Issue description
FriendlyUrlSearch field is missing values in the Blogs_AK and InternalPages_AK SharePoint lists.

### What's the expected change?
- FriendlyUrlSearch field to have a value in it.

### What's the current functionality?
- There is no value in the FriendlySearchUrl field for Blogs_AK or InternalPages_AK.

### Additional details / screenshot
- FriendlyUrlSearch value should be the same as the FriendlyUrl value.
- The FoundationNews_AK SharePoint list is a good example of what the expected result should look like.
![blogsemptyfield_720](https://github.com/NCIOCPL/akumina-mynci/assets/110186168/19d3d7e7-61a2-4049-87b3-7bf2d5d91348)
![foundationnewslist_720](https://github.com/NCIOCPL/akumina-mynci/assets/110186168/070b4330-53d4-476f-99e5-69c14e8710bf)

**Comment by erikscottmeyer** [comment]
Fixed.
