### ISSUE TITLE
Blog import changes

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/akumina-mynci#68]
- Blog Series from Drupal should be added as a Tag in SharePoint
- New fields Contact Person 1 and Contact Person 2 should receive the 2 "Contacts for this Content" from Drupal
    - Need to verify how we specify the person, hopefully same way as other user fields
    - Contacts no longer need to be appended to the body content
- New field Organization Owner should receive the "Content Owner (Organization)" field from Drupal
    - Currently terms aren't populating in this field, so need to fix that
    - Can leave this also going to Department
- Issue #67

**Comment by erikscottmeyer** [comment]
Done.
