### ISSUE TITLE
Event import changes

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/akumina-mynci#70]
- Location (Campus) from Drupal should map to Region in SharePoint
    - This is a metadata field
    - The values from Drupal are now all there
- New fields Contact Person 1 and Contact Person 2 should receive the 2 "Contacts for this Content" from Drupal
    - Need to verify how we specify the person, hopefully same way as other user fields
    - Contacts no longer need to be appended to the body content
- Content Owner (Organization) from Drupal should go to Department in SharePoint
- New field Organization Owner in SharePoint should also receive the "Content Owner (Organization)" field from Drupal
    - Currently terms aren't populating in this field, so need to fix that

**Comment by erikscottmeyer** [comment]
Done.
