### ISSUE TITLE
Internal pages import changes

### ISSUE THREAD

**Issue by jfrank-nih** [NCIOCPL/akumina-mynci#71]
- Short description from Drupal should be going to Summary in addition to Search Description
    - Was this a length issue?
- New fields Contact Person 1 and Contact Person 2 should receive the 2 "Contacts for this Content" from Drupal
    - Need to verify how we specify the person, hopefully same way as other user fields
    - Contacts no longer need to be appended to the body content
- Content Owner (Organization) from Drupal should go to Department in SharePoint
- New field Organization Owner in SharePoint should also receive the "Content Owner (Organization)" field from Drupal
    - Currently terms aren't populating in this field, so need to fix that

**Comment by erikscottmeyer** [comment]
Done.
